# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(380, 425)
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 381, 421))
        self.widget.setObjectName("widget")
        self.lb_foto = QtWidgets.QLabel(parent=self.widget)
        self.lb_foto.setGeometry(QtCore.QRect(40, 30, 300, 371))
        self.lb_foto.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0.4375 rgba(45, 103, 152, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius: 20px;")
        self.lb_foto.setText("")
        self.lb_foto.setObjectName("lb_foto")
        self.lb_dark = QtWidgets.QLabel(parent=self.widget)
        self.lb_dark.setGeometry(QtCore.QRect(40, 30, 300, 371))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        self.lb_dark.setFont(font)
        self.lb_dark.setStyleSheet("background-color: rgba(0, 0, 0, 100);\n"
"border-radius: 20px;")
        self.lb_dark.setText("")
        self.lb_dark.setObjectName("lb_dark")
        self.lb_login = QtWidgets.QLabel(parent=self.widget)
        self.lb_login.setGeometry(QtCore.QRect(140, 90, 90, 40))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        self.lb_login.setFont(font)
        self.lb_login.setStyleSheet("color: rgb(255, 255, 255);")
        self.lb_login.setObjectName("lb_login")
        self.le_login = QtWidgets.QLineEdit(parent=self.widget)
        self.le_login.setGeometry(QtCore.QRect(90, 150, 200, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_login.setFont(font)
        self.le_login.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(105, 118, 132,255);\n"
"color: rgba(255,255,255,230);\n"
"padding-bottom:7px;")
        self.le_login.setObjectName("le_login")
        self.le_password = QtWidgets.QLineEdit(parent=self.widget)
        self.le_password.setGeometry(QtCore.QRect(90, 210, 200, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_password.setFont(font)
        self.le_password.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(105, 118, 132,255);\n"
"color: rgba(255,255,255,230);\n"
"padding-bottom:7px;")
        self.le_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.le_password.setObjectName("le_password")
        self.but_login = QtWidgets.QPushButton(parent=self.widget)
        self.but_login.setGeometry(QtCore.QRect(90, 280, 200, 40))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(False)
        self.but_login.setFont(font)
        self.but_login.setStyleSheet("\n"
"QPushButton#but_login{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"color: rgba(255, 255, 255, 210);\n"
"border-radius: 20px;\n"
"}\n"
"QPushButton#but_login:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"}\n"
"\n"
"QPushButton#but_login:pressed{\n"
"panding-left: 5px;\n"
"panding-top: 5px;\n"
"background-color: rgba(105, 118, 132, 200)\n"
"}")
        self.but_login.setObjectName("but_login")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lb_login.setText(_translate("Form", "Log In"))
        self.le_login.setPlaceholderText(_translate("Form", "User Name"))
        self.le_password.setPlaceholderText(_translate("Form", "Password"))
        self.but_login.setText(_translate("Form", "L o g i n"))
